# Generated by Django 4.2.20 on 2025-05-24 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('table', 'date', 'time')},
        ),
    ]
