# Generated by Django 4.2.20 on 2025-05-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_table', '0002_alter_booking_options_alter_booking_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(choices=[('Starter', 'Starter'), ('Pasta', 'Pasta'), ('Pizza', 'Pizza'), ('Dessert', 'Dessert'), ('Drinks', 'Drinks')], max_length=20)),
            ],
        ),
    ]
